
- name: "Installer | Executing {{ current_stage }} for {{ service_item.name }}"
  become: true
  shell: "{{ cmd_item }}"
  loop: "{{ service_item[current_stage] | default([]) }}"
  loop_control:
    loop_var: cmd_item
  args:
    creates: "{{ service_item.check_file if (service_item.check_file is defined and service_item.check_file != '') else omit }}"
  when: 
    - service_item[current_stage] is defined
    - service_item[current_stage] | length > 0
